# Generated by Django 6.0.4 on 2026-05-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo_incidente', models.CharField(choices=[('falla_mecanica', 'Falla mecánica'), ('falla_electrica', 'Falla eléctrica'), ('desvio_calidad', 'Desvío de calidad'), ('accidente', 'Accidente'), ('casi_accidente', 'Casi accidente'), ('mantenimiento_preventivo', 'Mantenimiento preventivo'), ('problema_operativo', 'Problema operativo'), ('otro', 'Otro')], max_length=50)),
                ('otro_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20)),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=20)),
                ('sector_ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='reportes.area')),
            ],
        ),
    ]
