# Generated by Django 6.0.4 on 2026-05-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidente', models.CharField(choices=[('bug', 'Bug'), ('mejora', 'Mejora'), ('soporte', 'Soporte')])),
                ('area', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=250)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
