# Generated by Django 6.0.4 on 2026-05-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporte_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='area',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')]),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo_incidente',
            field=models.CharField(choices=[('bug', 'Bug'), ('mejora', 'Mejora'), ('soporte', 'Soporte')]),
        ),
    ]
