# Generated by Django 6.0.4 on 2026-05-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_reporte_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo_incidente',
            field=models.CharField(choices=[('bug', 'Bug'), ('mejora', 'Mejora'), ('soporte', 'Soporte')], max_length=20),
        ),
    ]
