# Generated by Django 6.0.4 on 2026-05-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
